workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    environment:
      node: 18.17.1
      android_signing:
        - keystoreFile: remi.keystore
          keystorePassword: $KEYSTORE_PASSWORD
          keyAlias: $KEY_ALIAS
          keyPassword: $KEY_PASSWORD
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.yourdomain.remi"
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Set up local properties
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Build Android release
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
